# Site settings
title: jekyll themes
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: kidd82483134
github_username:  jinny-c

# Build settings
markdown: kramdown
permalink: pretty

all_categories: [
["android", "Android开发","/posts/android.html"], 
["program", "软件编程","/posts/program.html"],
["read", "读书笔记","/posts/read.html"], 
["other", "杂记","/posts/other.html"],
["about", "关于","/about.html"]
]

port: 4001
